title: Vibha Govind Hegde
description: Portfolio Website

url: https://vi31.github.io

# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact
    - title: Portfolio
      url: /portfolio

social:
    github: vi31
    email: vihegde@ucdavis.edu
    linkedin: vihegde31
    

google_analytics: "UA-58263416-1"

disqus:
    shortname: Vibha
